### ISSUE TITLE
Does not work in ES 5.1.1

### ISSUE THREAD

**Issue by JTrotta** [jurgc11/es-change-feed-plugin#3]
May this plugin updated to work with ES 5.1.1?

**Comment by jurgc11** [comment]
Support for 5.x versions isn't a straight forward change. It looks like some of the APIs used have changed. I'll be looking again at in the next couple of weeks though.

Regards,
Chris

**Comment by EugeneKha** [comment]
Any update on this?

Regards,
Eugene

**Comment by jurgc11** [comment]
Sorry, no. It's still on the list, but probably not for the next month or so.

**Comment by jurgc11** [comment]
I've published a version for 5.3.2 and 5.4.0. Building versions for 5.0.x, 5.1.x and 5.2.x should be fairly straight forward if you still need them.
