### ISSUE TITLE
Fail to install with 2.4.1

### ISSUE THREAD

**Issue by huawangpp** [jurgc11/es-change-feed-plugin#4]
Can we release a build with 2.4.1? I'm getting the following error trying to install in on ES 2.4.1 - 

ERROR: Plugin [es-changes-feed-plugin] is incompatible with Elasticsearch [2.4.1]. Was designed for version [2.4.0]

**Comment by jurgc11** [comment]
Unfortunately Elasticsearch plugins are tied to a specific Elasticsearch release, right down to the patch version AFAIK. That means building a release for every Elasticsearch version which unfortunately I don't have time for. 

However, it's pretty easy to build your own version. All you need to do is change the elasticsearch.version property in [plugin-security.policy](https://github.com/jurgc11/es-change-feed-plugin/blob/master/src/main/resources/plugin-security.policy) first. Alternatively if you don't want to build it yourself, you could just modify that file directly in the zip file.
