### ISSUE TITLE
[Question] How to use with Node Client

### ISSUE THREAD

**Issue by singhpratyush** [jurgc11/es-change-feed-plugin#5]
I am creating elasticsearch cluster using `NodeBuilder` module. Is there a way to use this plugin in my setup?

**Comment by jurgc11** [comment]
Hi Pratyush,

I'm afraid I don't have any experience of using NodeBuilder beyond the very basics. 

Chris

**Comment by singhpratyush** [comment]
@jurgc11: Thank you for your response. You may close this if you feel like.
